name: on pull request required check
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  merge-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      - run: date
      - run: exit 0
  auto-merge-pr:
    needs: merge-check
    if: github.event.pull_request.user.login == 'irof'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - run: gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch
