name: on pull request required check
on:
  pull_request:
    branches: [ "main" ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
  merge-check:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
